spring:
  application:
    name: email-service
  mail:
    host: smtp.qq.com
    username: 1554909254@qq.com
    password: fwbabmcaodxkjdgi
    default-encoding: utf-8
  redis:
    host: 47.111.240.78
    port: 6379
    password: "1564335wang"
    jedis:
      pool:
        max-active: 20
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

activeServerUrl: http://localhost:8762/email/active/account/











