spring:
  application:
    name: regist-service

  datasource:
    url: jdbc:mysql:///qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: "root"
    password: "0000"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8763
