spring:
  application:
    name: sso-web

  redis:
    host: 47.111.240.78
    port: 6379
    password: "1564335wang"
    jedis:
      pool:
        max-active: 20

server:
  port: 7767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
